import { createServiceClient } from '@/lib/supabase/server'
import { generateSlug } from '@/lib/utils/slug'

const projects = [
  {
    title: 'FarmConnect',
    description: 'Digital marketplace connecting Rwandan farmers directly with buyers, eliminating middlemen and increasing farmer profits.',
    content: 'A comprehensive platform built with Next.js and Supabase that digitizes the agricultural supply chain in Rwanda. Features real-time pricing, order management, and mobile payment integration.',
    category: 'large',
    tags: ['agriculture', 'marketplace', 'fintech'],
    tech_stack: ['Next.js', 'TypeScript', 'Supabase', 'Tailwind CSS'],
    image_url: 'https://images.unsplash.com/photo-1574943320219-553eb213f72d?w=800&h=500&fit=crop',
    demo_url: 'https://farmconnect.rw',
    github_url: 'https://github.com/HamedProDev',
    featured: true,
    is_published: true,
    order_index: 1,
  },
  {
    title: 'MindCare',
    description: 'Mental health support platform providing AI-powered wellness assessments and connects users with professional therapists.',
    content: 'A JavaScript-based mental health website designed for anyone, especially students. Features mood tracking, journaling, therapist matching, and crisis support resources.',
    category: 'large',
    tags: ['healthcare', 'AI', 'mental-health'],
    tech_stack: ['JavaScript', 'React', 'Node.js', 'MongoDB'],
    image_url: 'https://images.unsplash.com/photo-1559757175-5700dde675bc?w=800&h=500&fit=crop',
    demo_url: '',
    github_url: 'https://github.com/HamedProDev/mindcare',
    featured: true,
    is_published: true,
    order_index: 2,
  },
  {
    title: 'AgriSmart',
    description: 'Farm management system that tracks and manages all farm operations including crop planning, inventory, and financial records.',
    content: 'A comprehensive farm management solution with dashboards for crop tracking, weather integration, expense management, and yield analytics.',
    category: 'large',
    tags: ['agriculture', 'dashboard', 'management'],
    tech_stack: ['TypeScript', 'Vue.js', 'Firebase'],
    image_url: 'https://images.unsplash.com/photo-1625246333195-78d9c38ad449?w=800&h=500&fit=crop',
    github_url: 'https://github.com/HamedProDev/AgriSmart',
    featured: true,
    is_published: true,
    order_index: 3,
  },
  {
    title: 'HahuMovies',
    description: 'Online movie streaming platform with curated content, watchlists, and personalized recommendations.',
    content: 'A full-featured movie streaming web app with search, filtering, user accounts, watch history, and responsive video player.',
    category: 'large',
    tags: ['streaming', 'entertainment', 'web-app'],
    tech_stack: ['TypeScript', 'React', 'Node.js'],
    image_url: 'https://images.unsplash.com/photo-1574375927938-d5a98e8d7e28?w=800&h=500&fit=crop',
    github_url: 'https://github.com/HamedProDev/hahumovies',
    featured: false,
    is_published: true,
    order_index: 4,
  },
  {
    title: 'Kwanda EMS',
    description: 'Enterprise management system for Kwanda Facility operations, streamlining workflows and team collaboration.',
    content: 'Full enterprise management solution with project tracking, HR modules, inventory management, and real-time analytics dashboards.',
    category: 'large',
    tags: ['enterprise', 'management', 'SaaS'],
    tech_stack: ['Next.js', 'Express', 'PostgreSQL', 'Tailwind CSS'],
    image_url: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800&h=500&fit=crop',
    github_url: 'https://github.com/HamedProDev',
    featured: true,
    is_published: true,
    order_index: 5,
  },
  {
    title: 'Claude Code',
    description: 'Mini Claude-style code chatbot with custom API integration for AI-powered coding assistance.',
    content: 'A demo chatbot application that integrates with AI models to provide coding assistance, code review, and development suggestions.',
    category: 'large',
    tags: ['AI', 'chatbot', 'developer-tools'],
    tech_stack: ['JavaScript', 'React', 'OpenAI API'],
    image_url: 'https://images.unsplash.com/photo-1677442136019-21780ecad995?w=800&h=500&fit=crop',
    github_url: 'https://github.com/HamedProDev/Claude-Code',
    featured: false,
    is_published: true,
    order_index: 6,
  },
  {
    title: 'SocialCash',
    description: 'Social media monetization platform enabling users to earn money through content creation and engagement.',
    content: 'A TypeScript-based platform for social media monetization with referral system, task completion rewards, and withdrawal management.',
    category: 'large',
    tags: ['fintech', 'social-media', 'monetization'],
    tech_stack: ['TypeScript', 'React', 'Firebase'],
    image_url: 'https://images.unsplash.com/photo-1611162617474-5b21e879e113?w=800&h=500&fit=crop',
    github_url: 'https://github.com/HamedProDev/social-cash',
    featured: false,
    is_published: true,
    order_index: 7,
  },
  {
    title: 'Rumuri Intelligence',
    description: 'OSINT intelligence gathering tool for security research and digital investigation.',
    content: 'An intelligence platform built with TypeScript for open-source intelligence gathering, data analysis, and threat assessment.',
    category: 'large',
    tags: ['security', 'OSINT', 'intelligence'],
    tech_stack: ['TypeScript', 'Node.js', 'Python'],
    image_url: 'https://images.unsplash.com/photo-1550751827-4bd374c3f58b?w=800&h=500&fit=crop',
    github_url: 'https://github.com/HamedProDev/rumuri-intelligence',
    featured: false,
    is_published: true,
    order_index: 8,
  },
  {
    title: 'Evil-Droid Enhanced',
    description: 'Comprehensive penetration testing framework for ethical hacking and Android security assessment.',
    content: 'Enhanced version of Evil-Droid with bug fixes, improved functionality, and interactive menu system for security researchers.',
    category: 'large',
    tags: ['security', 'pentesting', 'android'],
    tech_stack: ['Shell', 'Python', 'Android'],
    image_url: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=800&h=500&fit=crop',
    github_url: 'https://github.com/HamedProDev/evil-droid-enhanced',
    featured: false,
    is_published: true,
    order_index: 9,
  },
  {
    title: 'Kinyarwanda Datasets',
    description: 'Collection of Kinyarwanda language datasets for NLP research and AI model training.',
    content: 'Comprehensive Kinyarwanda text datasets for machine learning, NLP tasks, and AI model training, contributed to the open-source community.',
    category: 'large',
    tags: ['AI', 'NLP', 'datasets', 'open-source'],
    tech_stack: ['Python', 'NLP', 'Machine Learning'],
    image_url: 'https://images.unsplash.com/photo-1555949963-aa79dcee981c?w=800&h=500&fit=crop',
    github_url: 'https://github.com/HamedProDev/Kinyarwanda-datasets',
    featured: true,
    is_published: true,
    order_index: 10,
  },
  {
    title: 'Desert Runner',
    description: 'Browser-based endless runner game built with Vue.js and Canvas API.',
    content: 'An addictive browser game with procedurally generated obstacles, score tracking, and smooth animations using Vue.js.',
    category: 'mini',
    tags: ['game', 'browser', 'vue'],
    tech_stack: ['Vue.js', 'JavaScript', 'Canvas API'],
    image_url: 'https://images.unsplash.com/photo-1556438064-2d7646166914?w=800&h=500&fit=crop',
    github_url: 'https://github.com/HamedProDev/desert-runner',
    featured: false,
    is_published: true,
    order_index: 11,
  },
  {
    title: 'Islamic Quran AI',
    description: 'AI-powered Quran application with recitation, translation, and tafsir features for Muslims worldwide.',
    content: 'A Kotlin-based mobile application with AI-powered Quran search, verse explanations, recitation guidance, and personalized reading plans.',
    category: 'mini',
    tags: ['mobile', 'AI', 'islamic'],
    tech_stack: ['Kotlin', 'Android', 'AI'],
    image_url: 'https://images.unsplash.com/photo-1585036156171-384164a8c141?w=800&h=500&fit=crop',
    github_url: 'https://github.com/HamedProDev/islam-quran-ai-app',
    featured: true,
    is_published: true,
    order_index: 12,
  },
  {
    title: 'E-Commerce Kotlin',
    description: 'Modern e-commerce mobile application built with Kotlin and Material Design.',
    content: 'A full-featured e-commerce app with product catalog, cart management, checkout flow, order tracking, and user authentication.',
    category: 'mini',
    tags: ['mobile', 'e-commerce', 'kotlin'],
    tech_stack: ['Kotlin', 'Android', 'Firebase'],
    image_url: 'https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=800&h=500&fit=crop',
    github_url: 'https://github.com/HamedProDev/modern-ecommerce-kotlin',
    featured: false,
    is_published: true,
    order_index: 13,
  },
  {
    title: 'Full Admin Portfolio',
    description: 'Full CRUD portfolio builder with admin panel for developers to showcase their work.',
    content: 'A dynamic portfolio system with admin dashboard for managing projects, skills, and blog posts — perfect for developers.',
    category: 'mini',
    tags: ['portfolio', 'admin', 'CRUD'],
    tech_stack: ['React', 'Node.js', 'MongoDB'],
    image_url: 'https://images.unsplash.com/photo-1467232004584-a241de8bcf5d?w=800&h=500&fit=crop',
    github_url: 'https://github.com/HamedProDev/full-admin-control-dynamic-portfolio',
    featured: false,
    is_published: true,
    order_index: 14,
  },
  {
    title: 'ES Mukingi Website',
    description: 'School website for ES Mukingi built with Vue.js, featuring events, resources, and student portals.',
    content: 'A Vue.js school website with event calendar, resource library, student registration, and admin content management.',
    category: 'school',
    tags: ['education', 'school', 'vue'],
    tech_stack: ['Vue.js', 'JavaScript', 'CSS'],
    image_url: 'https://images.unsplash.com/photo-1580582932707-520aed937b7b?w=800&h=500&fit=crop',
    github_url: 'https://github.com/HamedProDev/es-mukingi',
    featured: false,
    is_published: true,
    order_index: 15,
  },
  {
    title: 'Tic-Tac-Toe Game',
    description: 'Classic tic-tac-toe game with AI opponent and multiplayer support, built with Vue.js.',
    content: 'A Vue.js implementation of tic-tac-toe with unbeatable AI using minimax algorithm and local multiplayer mode.',
    category: 'mini',
    tags: ['game', 'vue', 'AI'],
    tech_stack: ['Vue.js', 'JavaScript'],
    image_url: 'https://images.unsplash.com/photo-1611532736597-de2d4265fba3?w=800&h=500&fit=crop',
    github_url: 'https://github.com/HamedProDev/Tic-tac-toe-class-game',
    featured: false,
    is_published: true,
    order_index: 16,
  },
  {
    title: 'PaySmart Mobile',
    description: 'Mobile payment solution for small businesses in East Africa with QR code payments and analytics.',
    content: 'Digital payments platform for SMEs with QR code scanning, transaction history, business analytics, and multi-currency support.',
    category: 'large',
    tags: ['fintech', 'payments', 'mobile'],
    tech_stack: ['React Native', 'Firebase', 'Node.js'],
    image_url: 'https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=800&h=500&fit=crop',
    github_url: 'https://github.com/HamedProDev',
    featured: false,
    is_published: true,
    order_index: 17,
  },
  {
    title: 'Iga Vue.js',
    description: 'Educational platform teaching Vue.js in Kinyarwanda with interactive lessons and exercises.',
    content: 'A Vue.js tutorial platform localized in Kinyarwanda, featuring progressive lessons, code examples, and interactive exercises.',
    category: 'mini',
    tags: ['education', 'vue', 'kinyarwanda'],
    tech_stack: ['Vue.js', 'TypeScript', 'Tailwind CSS'],
    image_url: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=800&h=500&fit=crop',
    github_url: 'https://github.com/HamedProDev/Iga-Vue-js',
    featured: false,
    is_published: true,
    order_index: 18,
  },
]

export async function POST() {
  try {
    const supabase = createServiceClient()
    const results: string[] = []

    // Delete all existing projects and their data
    const { data: existing } = await supabase.from('projects').select('id')
    if (existing && existing.length > 0) {
      await supabase.from('projects').delete().neq('id', '00000000-0000-0000-0000-000000000000')
      results.push(`Deleted ${existing.length} old projects`)
    }

    // Insert new projects
    for (const p of projects) {
      const slug = generateSlug(p.title)
      const { error } = await supabase.from('projects').insert({ ...p, slug })
      results.push(error ? `ERROR: ${p.title} — ${error.message}` : `OK: ${p.title}`)
    }

    return Response.json({ success: true, results })
  } catch (error: any) {
    return Response.json({ success: false, error: error.message }, { status: 500 })
  }
}
