services:
  - type: web
    name: hamedpro
    runtime: node
    plan: free
    buildCommand: npm install --legacy-peer-deps && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20.20.2
      - key: NEXT_PUBLIC_SITE_NAME
        value: HamedProDev
      - key: MONGODB_URI
        value: "mongodb+srv://hamedprodev:fable5yaje@hamedprodev.aiwnhac.mongodb.net/hamedpro_dev?retryWrites=true&w=majority&appName=HamedProDev"
      - key: NEXTAUTH_URL
        value: "https://hamedprodev.onrender.com"
      - key: AUTH_URL
        value: "https://hamedprodev.onrender.com"
      - key: AUTH_SECRET
        value: "2LF20tNXRCmCrG54/vRbWVxBMYo+6JFrWymfy8XC7no="
      - key: NEXTAUTH_SECRET
        value: "2LF20tNXRCmCrG54/vRbWVxBMYo+6JFrWymfy8XC7no="
      - key: NEXT_PUBLIC_APP_URL
        fromService:
          name: hamedpro
          type: web
          property: host
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: GITHUB_CLIENT_ID
        sync: false
      - key: GITHUB_CLIENT_SECRET
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME
        sync: false
      - key: RESEND_API_KEY
        sync: false
      - key: RESEND_FROM_EMAIL
        value: hello@hamedprodev.onrender.com
      - key: UPSTASH_REDIS_REST_URL
        sync: false
      - key: UPSTASH_REDIS_REST_TOKEN
        sync: false
      - key: ADMIN_EMAIL
        value: hamedpro.work@gmail.com
